### ISSUE TITLE
Readthedocs minor issues, e.g. example needs numpy import

### ISSUE THREAD

**Issue by baogorek** [oseiskar/simdkalman#1]
Not that anybody who can figure out the Kalman filter won't be able to figure out how to import numpy, but for completeness of the example you might as well add the import:

https://simdkalman.readthedocs.io/en/latest/

I'm personally partial to

    import numpy as np

Also, predict is spelled as "precit":

"See smooth and precit"

Thanks for writing these examples up.

**Comment by oseiskar** [comment]
Hmm, Github was a bit too eager to close this, the fix also included https://github.com/oseiskar/simdkalman/commit/68656437e9d832964a49edb0934f278646fe296d and https://github.com/oseiskar/simdkalman/commit/36ac2d2c1b01b815b6b10196b482b0195da7fefb

Thanks for reporting. I also think that `import numpy as np` is almost a "standard". However, the corresponding thing for `import numpy.random` is not clear to me.
