### ISSUE TITLE
Shape convention check

### ISSUE THREAD

**Issue by microprediction** [oseiskar/simdkalman#17]
Hello Otto. 
  In line 200 of kalmanfilter the following dimension check is made, along with others: 
   n_states = state_transition.shape[0]
 Should this be 
  n_states = state_transition.shape[-2]
 to support the use of multiple transition matrices, or is that not supported? 
Peter

**Comment by microprediction** [comment]
You know what, never mind I should be able to answer this along the lines of
[update](https://github.com/microprediction/simdkalman/blob/master/examples/multiple_systems_update.py)

**Comment by microprediction** [comment]
See PR

**Comment by oseiskar** [comment]
Was actually fixed by https://github.com/oseiskar/simdkalman/pull/18 (but forgot to tag this issue in the squash-merged commit)
