### ISSUE TITLE
Possible minor inconsistency in dimensions?

### ISSUE THREAD

**Issue by microprediction** [oseiskar/simdkalman#19]
I was in the process of writing some unit tests for the multi-dim usage and noticed a possible minor inconsistency. Both KalmanFilter.predict and KalmanFilter.update require the initial means to take a certain shape. The latter preserves this shape in the output results object. However, the .predict method transposes the last two dimensions. Thus the shape of the means going in isn't the same as going out. If this output is merely intended as reporting that doesn't matter, but as you can see from this [test script](https://github.com/microprediction/timemachines/blob/main/tests/smdk/test_individual_steps.py) there *might* be a slight inconsistency here. However, perhaps I misunderstand the intent or am abusing the usage somehow. 

LMK if you want this test script in a notebook or PR into simdkalman.

**Comment by oseiskar** [comment]
Thanks! I'll take a closer look later this week (and review #18 as well)

**Comment by oseiskar** [comment]
This actually might be just a confusion between `predict` & `predict_next`, see https://github.com/oseiskar/simdkalman/pull/18#discussion_r683613205

**Comment by oseiskar** [comment]
Works as intended with `predict_next`, even though the terminology is indeed confusing here. See
 * This test: https://github.com/oseiskar/simdkalman/commit/8c9364d0a501e15493d60a0fc50ae05489063ba8
 * and: https://github.com/oseiskar/simdkalman/blob/8c9364d0a501e15493d60a0fc50ae05489063ba8/examples/multiple_systems_single_step.py#L48-L58
